# Generated by Django 4.1.7 on 2023-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='has',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('empid', models.ForeignKey(db_column='empid', on_delete=django.db.models.deletion.CASCADE, to='polls.employee')),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='polls.responsibilities')),
            ],
        ),
    ]
