# Generated by Django 4.1.7 on 2023-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_responsibilities_has'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilities',
            name='description',
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='criteria1',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='criteria2',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='criteria3',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
