# Generated by Django 4.1.7 on 2023-05-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_responsibilities_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsibilities',
            old_name='criteria1',
            new_name='criteria',
        ),
        migrations.RemoveField(
            model_name='responsibilities',
            name='criteria2',
        ),
        migrations.RemoveField(
            model_name='responsibilities',
            name='criteria3',
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='earned',
            field=models.BooleanField(default=False),
        ),
    ]
