# Generated by Django 4.1.7 on 2023-05-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilities',
            name='title',
        ),
        migrations.AddField(
            model_name='responsibilities',
            name='cid',
            field=models.ForeignKey(db_column='cid', default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.category'),
            preserve_default=False,
        ),
    ]
