# Generated by Django 4.1.7 on 2023-06-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_responsibilities_title_responsibilities_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibilities',
            name='earned',
        ),
    ]
