# Generated by Django 4.1.7 on 2023-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_responsibilities_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='has',
            name='score',
            field=models.BooleanField(default=False),
        ),
    ]
